### ISSUE TITLE
Can you add TCP support?

### ISSUE THREAD

**Issue by MDAR** [gertst/node-red-contrib-velbus#1]
Hello Gert

I'm always keen to support anyone working with Velbus.

In order for me to play around with your work, I need it to share a connect to the Serial port (ttyACM0)

Currently I have VelServ using that and sharing it out to TCP port 6000

Best wishes,

Stuart

**Comment by gertst** [comment]
Sure, in fact I'm in the middle of adding it 😉

But as this is a side project, I can not spend as much time on it as I
wanted to. So it will probably take a few more months, because I also plan
to refactor quite a lot.

Cheers,
Gert

Op ma 8 jul. 2019 3:32 p.m. schreef MDAR Ltd <notifications@github.com>:

**Comment by MDAR** [comment]
Hi

When you get the TCP connection nailed, please give me a shout and I'll give you the remote connection details for my demo rig, which I can hang any modules you want to test onto.


I'm sure by now you know how to get hold of me.

**Comment by ggaljoen** [comment]
Hi Gert,

Did you find some free time to work on this feature? 
Alvast bedankt!
Gg

**Comment by gertst** [comment]
Hi,

I'm working on it but it's still not stable and feature rich enough to
publish...

But I'm spending some more time on it lately so I hope to release something
in the coming weeks. No guaranties though 😉

Op wo 4 mrt. 2020 19:25 schreef ggaljoen <notifications@github.com>:

**Comment by gertst** [comment]
TCP support added!
The changes are pushed to github and npm. It's a matter of hours before Node-Red picks up the new version.
