### ISSUE TITLE
Velbus Relay Node status bug (or feature request)

### ISSUE THREAD

**Issue by smoothquark** [gertst/node-red-contrib-velbus#2]
Hi. Not sure if this is a bug or an unsupported use scenario. For a project I am playing with, I require to know the status of various relays. I am therefore using the relay node, as is, with velserv and address and channel configured. The odd thing is that for all my relay modules, a relay node pointing to Channel 1 works fine - the status changes to true/false depending on whether it is closed or not. For the other 3 channels, the status does not change.

So, I am not sure if the relay node could (or meant to) be used this way?

**Comment by MDAR** [comment]
@gertst 

I can confirm that I can replcate this behaviour.

The updates for each channel are being recieved and the time is changing at each node, but the status is not changing for anything other than Ch1 (of a VMB4RYLD)

The sequence I used was

Channel 1 - ON
Channel 1 - OFF

Channel 2 - ON
Channel 2 - OFF

Channel 3 - ON
Channel 3 - OFF

Channel 4 - ON
Channel 4 - OFF

Channel 5 - ON
Channel 5 - OFF


(so 10 packets, where only packets 1 and 2 show the correct change in the on state)

![image](https://user-images.githubusercontent.com/10905891/93331076-a686a680-f817-11ea-9121-617b75d3808f.png)


```
9/16/2020, 12:06:24 PMnode: 61b65d21.f81094
msg : Object
object
payload: true
on: true
_msgid: "e5e3a995.933118"
9/16/2020, 12:06:25 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "e7fb08e8.732c98"
9/16/2020, 12:06:29 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "62388ac0.de1c84"
9/16/2020, 12:06:30 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "c15b1c89.705d9"
9/16/2020, 12:06:33 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "ff4f60b8.59ff8"
9/16/2020, 12:06:33 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "b2edb51a.40be78"
9/16/2020, 12:06:36 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "89ffa389.30a2"
9/16/2020, 12:06:41 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "bc3af70e.95bd68"
9/16/2020, 12:06:42 PMnode: 61b65d21.f81094
msg : Object
object
payload: false
on: false
_msgid: "78812e9b.10407"
```

@smoothquark 

While Gert works his magic on this issue, the following flow will get you the status for all 5 channels of a relay.

![image](https://user-images.githubusercontent.com/10905891/93330976-835bf700-f817-11ea-8a4e-8ee3acd0736d.png)


```
[
    {
        "id": "7729c539.1d731c",
        "type": "velbus-receive-raw-bytes",
        "z": "8aafde9e.377",
        "name": "",
        "connector": "cc43cf41.a9ec4",
        "command": "",
        "commandType": "251",
        "address": "",
        "addressType": "2",
        "x": 480,
        "y": 600,
        "wires": [
            [
                "76860da5.322984",
                "3a2f4375.d7622c",
                "69ff542d.fd809c",
                "f0031427.a93cd8",
                "e75431a4.05901",
                "ef93a5f9.63f058"
            ]
        ]
    },
    {
        "id": "76860da5.322984",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "msg",
        "x": 710,
        "y": 680,
        "wires": []
    },
    {
        "id": "3a2f4375.d7622c",
        "type": "switch",
        "z": "8aafde9e.377",
        "name": "Channel 1",
        "property": "payload.dataBytesArray[1]",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "1",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 690,
        "y": 240,
        "wires": [
            [
                "fb1570e7.afe33"
            ]
        ]
    },
    {
        "id": "fb1570e7.afe33",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload.dataBytesArray[3]",
        "targetType": "msg",
        "statusVal": "payload.dataBytesArray[3]",
        "statusType": "auto",
        "x": 970,
        "y": 240,
        "wires": []
    },
    {
        "id": "ef93a5f9.63f058",
        "type": "switch",
        "z": "8aafde9e.377",
        "name": "Channel 2",
        "property": "payload.dataBytesArray[1]",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "2",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 690,
        "y": 320,
        "wires": [
            [
                "f24e8e40.2c37c"
            ]
        ]
    },
    {
        "id": "f24e8e40.2c37c",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload.dataBytesArray[3]",
        "targetType": "msg",
        "statusVal": "payload.dataBytesArray[3]",
        "statusType": "auto",
        "x": 970,
        "y": 320,
        "wires": []
    },
    {
        "id": "e75431a4.05901",
        "type": "switch",
        "z": "8aafde9e.377",
        "name": "Channel 3",
        "property": "payload.dataBytesArray[1]",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "4",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 690,
        "y": 400,
        "wires": [
            [
                "66cafc29.1fb304"
            ]
        ]
    },
    {
        "id": "66cafc29.1fb304",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload.dataBytesArray[3]",
        "targetType": "msg",
        "statusVal": "payload.dataBytesArray[3]",
        "statusType": "auto",
        "x": 970,
        "y": 400,
        "wires": []
    },
    {
        "id": "f0031427.a93cd8",
        "type": "switch",
        "z": "8aafde9e.377",
        "name": "Channel 4",
        "property": "payload.dataBytesArray[1]",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "8",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 690,
        "y": 460,
        "wires": [
            [
                "b884ddb7.8293e"
            ]
        ]
    },
    {
        "id": "b884ddb7.8293e",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload.dataBytesArray[3]",
        "targetType": "msg",
        "statusVal": "payload.dataBytesArray[3]",
        "statusType": "auto",
        "x": 970,
        "y": 460,
        "wires": []
    },
    {
        "id": "69ff542d.fd809c",
        "type": "switch",
        "z": "8aafde9e.377",
        "name": "Channel 5",
        "property": "payload.dataBytesArray[1]",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "16",
                "vt": "num"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 690,
        "y": 540,
        "wires": [
            [
                "e59e18a5.d0e5e8"
            ]
        ]
    },
    {
        "id": "e59e18a5.d0e5e8",
        "type": "debug",
        "z": "8aafde9e.377",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload.dataBytesArray[3]",
        "targetType": "msg",
        "statusVal": "payload.dataBytesArray[3]",
        "statusType": "auto",
        "x": 970,
        "y": 540,
        "wires": []
    }
]
```

**Comment by smoothquark** [comment]
Been testing out the source... I am wondering if the fix is something as simple as this...
node-red/velbus-relay.js line 58:
Change:
this.isOn = Utils.bitAtGivenPosSetOrUnset(packet.getDataByte(3),channel);
to
this.isOn = packet.getDataByte(3);

Have tested it with 3 relays - I am now getting status for all channels and all channels toggle too.

**Comment by gertst** [comment]
Hi @smoothquark,
Thanks for your comment and possible solution!

I'm using the relay node in my own setup on channel 2 and it's working as expected. But I'm using an old VMB4RY module and maybe the protocol slightly changed with newer modules. I don't have any other relay module, so I can't test, but if you let me know what relay module type you are using I can build in your below fix depending on the type.
Of course I am very happy to accept a pull request. More contributors to this code would be awesome ;-)

**Comment by MDAR** [comment]
@gertst 

I'm always happy to give you remote access to a demo unit if you want to test a module you don't have 😄

**Comment by smoothquark** [comment]
Thank you gertst. I have been doing more testing - the relay node correctly reports its status when Velbus buttons are physically pressed. When I use the button node, however, it has been erratic today with the wrong channels triggered. Was fine yesterday though (!) Shall test it a bit more...

**Comment by MDAR** [comment]
Hey @smoothquark 

There's a very good reason for that.

The Velbus protocol does some clever things at a base level.

For example, in order for a Relay to be used as an initiator, it reports it's status using two codes.

00 is a universal Button Status and Relay status FB

So I suspect what you're referring to is the ability to get the relay channel status using 00 ;-)

**Comment by smoothquark** [comment]
From VMB4RYLD PROTOCOL – edition 5, 

DATABYTE4 = Relay status
Contents		Relay status
B’xxxxxx00’	Relay channel off
B’xxxxxx01’	Relay channel on
B’xxxxxx11’	Relay channel interval timer on

I guess this explains why my little hack seems to (partially) work?

Anyway, the relay status seems to be always correct when I press Velbus buttons with actions pointing to the Velbus relays. However, when a Velbus pushbutton remains unlinked to a Velbus relay but addressed via node-red, for example, a short press, when the relay channel is a Channel 1, the pushbutton works correctly and the status on node-red is updated correctly as well. When the Channels are not 1, the relay will toggle correctly if its actual status is the the same as that on node-red, but the status then does not update (unlike for Channel 1). I shall play around with the code a bit more, but cannot seem to figure why it works for Channel 1 on the relay but not the other channels.

**Comment by smoothquark** [comment]
Hi again gertst. Had a look at the the VMB4RY protocol. DATABYTE4 = Relay status is indeed dependent on the relevant channel bit, so looks like the protocol has changed from VMB4RY to the VMB4RYLD. The VMB4RYNO and VMB4RYS use the same protocol as the VMB4RYLD. I suspect there are other protocol differences between the VMB4RY and VMB4RYLD which may explain why the pushbutton node updates the status on relay channels 1 but not the others on my VMB4RYLD.

**Comment by smoothquark** [comment]
I have submitted a pull request with a workaround which seems to be working for me. Shall be torture testing it soon to see if it works with my plans for my lounge lights...

**Comment by gertst** [comment]
> I have submitted a pull request with a workaround which seems to be working for me. Shall be torture testing it soon to see if it works with my plans for my lounge lights...

Thanks for your contribution @smoothquark , much appreciated! I'll have a look at it right now ;-)

**Comment by smoothquark** [comment]
Thanks @gertst. Closing now....
