### ISSUE TITLE
Node-RED v 1.2.9 Vs V1.3.4

### ISSUE THREAD

**Issue by MDAR** [gertst/node-red-contrib-velbus#5]
Hi

I've just set up a new machine and just can't get your lovely Velbus nodes to deploy and scan for new modules.

All I see in the modes is 
![image](https://user-images.githubusercontent.com/10905891/118651464-7bf15100-b7dd-11eb-8c6a-0225b2d448b6.png)

## Things I have tried

- I have restarted Node-RED
- Rebooted the whole machine
- Removed the Velbus nodes, restarted and added them back in, deployed & restarted

(All while watching the log in VelbusLink for any signs of scanning for new modules)

I don't think there was anything special that I did with Node-RED V1.2.9 that made it work. (which is still working happily on a different machine)

Node-RED 1.3.4 just refuses to do anything with Velbus.

Can you suggest anything I can look at / for to see what the issue is?

### Background....

I'm making the change to OpenHAB3, so instead of wiping a perfectly good machine, I have started again with a fresh machine.

Odroid C4
DietPi  V7.1.2
openHAB3

Node-RED V1.3.4 - with
openHAB3 & Velbus nodes

*************

Update

But the strange thing is that I've just setup a fresh machine with Ubuntu 20, OpenHAB3 and Node-RED V1.3.3 and it's working...
?????

**Comment by gertst** [comment]
That's strange indeed! I checked the release notes of V1.3.4 vs 1.3.3 and can't see any differences that could interfere with he Velbus module ... 

"Did you turn it off and on again?" :-P

**Comment by MDAR** [comment]
> "Did you turn it off and on again?" :-P

Ha Ha 😆 

Yes, I did give it a big kicking, a number of times.

But a completely fresh installation on another machine is working fine.


There is probably something strange going on, I'll wipe that original machine and start again

**Comment by gertst** [comment]
> But a completely fresh installation on another machine is working fine.

Happy to hear that :)
